name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cppcheck

      - name: Run linter
        run: |
          cppcheck --check-config --enable=all --suppress=missingIncludeSystem $(find src/ -name '*.c')

      - name: Build project
        run: make

      - name: Run tests
        run: make test

      - name: Clean up
        run: make clean
