name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy-to-dev:
    name: Deploy to Development Droplet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Validate Host
        run: |
          if [ -z "${{ secrets.DEV_HOST_IP }}" ]; then
            echo "Error: DEV_HOST_IP is not set."
            exit 1
          fi

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST_IP }}
          username: pine_user
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd /home/pine_user/Pine
            git pull origin main
            docker compose down
            docker compose up -d --build
