name: Deploy to Droplet

on:
  push:
    branches:
      - main
env:
  DEV_HOST_IP: ${{ env.DEV_HOST_IP }}

jobs:
  deploy-to-dev:
    name: Deploy to Development Droplet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DEV_HOST_IP }}
          username: pine_user
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd /home/pine_user/Pine
            git pull origin main
            docker compose down
            docker compose up -d --build
